import os
from typing import Any

import httpx
from dotenv import load_dotenv

load_dotenv()


def build_report_prompt(
    metrics: dict[str, Any],
    recommendations: list[str],
) -> str:
    return f"""
You are an ML reliability engineer.

Generate a concise professional model-health report from the verified results
below. Do not invent scores or claims.

Verified metrics:
{metrics}

Verified recommendations:
{recommendations}

Return the report with these headings:

1. Executive Summary
2. Reliability Diagnosis
3. Main Risks
4. Recommended Treatment
5. Deployment Recommendation

Use clear, professional language.
"""


def generate_fallback_report(
    metrics: dict[str, Any],
    recommendations: list[str],
) -> str:
    health_score = float(metrics.get("health_score", 0))
    grade = str(metrics.get("grade", "N/A"))
    deployment = str(
        metrics.get("deployment_status", "NOT EVALUATED")
    )

    noise = float(metrics.get("noise_stability", 0))
    missing = float(metrics.get("missing_stability", 0))
    outlier = float(metrics.get("outlier_stability", 0))
    drift = float(metrics.get("drift_stability", 0))

    risks = []

    if noise < 80:
        risks.append("The model is sensitive to noisy input values.")

    if missing < 80:
        risks.append(
            "The model becomes unstable when feature values are missing."
        )

    if outlier < 80:
        risks.append("Extreme values may change model predictions.")

    if drift < 80:
        risks.append(
            "Feature drift may reduce future production performance."
        )

    if not risks:
        risks.append(
            "No critical reliability weakness was detected "
            "under the supplied tests."
        )

    recommendation_text = "\n".join(
        f"- {item}" for item in recommendations
    ) or "- Continue monitoring model reliability."

    risk_text = "\n".join(
        f"- {item}" for item in risks
    )

    return f"""
1. Executive Summary

The model received a health score of {health_score}/100 with grade {grade}.
Its current deployment status is {deployment}.

2. Reliability Diagnosis

Noise stability: {noise}%
Missing-value stability: {missing}%
Outlier stability: {outlier}%
Drift stability: {drift}%

3. Main Risks

{risk_text}

4. Recommended Treatment

{recommendation_text}

5. Deployment Recommendation

The model should follow the deployment decision generated by ModelGuard AI.
Critical failed tests must be resolved before production deployment.
""".strip()


async def generate_llm_report(
    metrics: dict[str, Any],
    recommendations: list[str],
) -> dict[str, Any]:
    api_url = os.getenv("LLM_API_URL")
    api_key = os.getenv("LLM_API_KEY")
    model_name = os.getenv("LLM_MODEL")

    if not api_url or not api_key or not model_name:
        return {
            "provider": "fallback",
            "report": generate_fallback_report(
                metrics,
                recommendations,
            ),
        }

    prompt = build_report_prompt(
        metrics,
        recommendations,
    )

    payload = {
        "model": model_name,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You explain verified machine-learning reliability "
                    "results without inventing evidence."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        "temperature": 0.2,
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(
            timeout=40.0
        ) as client:
            response = await client.post(
                api_url,
                json=payload,
                headers=headers,
            )

            response.raise_for_status()
            data = response.json()

        report = data["choices"][0]["message"]["content"]

        return {
            "provider": "llm",
            "model": model_name,
            "report": report,
        }

    except (
        httpx.HTTPError,
        KeyError,
        IndexError,
        TypeError,
    ) as error:
        return {
            "provider": "fallback",
            "warning": (
                "LLM request failed; deterministic report was generated."
            ),
            "error": str(error),
            "report": generate_fallback_report(
                metrics,
                recommendations,
            ),
        }